### ISSUE TITLE
Android 10

### ISSUE THREAD

**Issue by somhi** [Softcatala/LanguageToolAndroidService#11]
Is the version on google play usable in Android 10?
I couldn't find info on how to enable it. 

Merci

**Comment by jordimas** [comment]
Yes, I use it everyday. However, as explained in Google Play, it does not work on devices on which vendors (like Samsung) have removed APIs or re-write the UI. It works well in Android One.

**Comment by somhi** [comment]
I have google pixel  XL first generation with Android 10.

While redacting this replay.... finally I found how to activate Language tool !!!!!   It's a bit different from what explained in google play.

I went to Settings > System > languages & text input > advanced options > spell checker > default spell checker
And here was my fault: I only touched the config gear button but instead it is needed to touch on the text itself to see what spell checkers are available.

Tested and it works!

Jordi
