### ISSUE TITLE
switch to JSON API

### ISSUE THREAD

**Issue by danielnaber** [Softcatala/LanguageToolAndroidService#5]
LT will soon be switching to a JSON-based API. It's documented at https://languagetool.org/http-api/swagger-ui/#/default. It might be a bit too early to rely on the format, but some time in the future we'll only support the new API and the old one will be turned off, so this software wilk need to be adapted to keep working.

**Comment by danielnaber** [comment]
We've set up a migration guide at https://languagetool.org/http-api/migration.php: the old API will be turned off in 4 months. Please let me know if you need help switching to the new API.

**Comment by danielnaber** [comment]
@jordimas any chance you could be working on this soon? Even tough it's still some time until we switch off the old API, Android causes most requests to the old API now.

**Comment by jordimas** [comment]
I will try to do the switch this weekend. I will keep you posted. Thanks. Jordi

**Comment by danielnaber** [comment]
About 90% of the queries from Android are now going to the JSON API. About the remaining 10%, I guess these are users that just don't update?

**Comment by jordimas** [comment]
That's correct. According to the Google Play Developer console 81.57% of the users are already in the latest version with JSON API. This should only get better over the next weeks. Regards

**Comment by danielnaber** [comment]
I think this can be closed.
