### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by Poussinou** [Softcatala/LanguageToolAndroidService#8]
Hi,

What's the license of this project?

If it's something open-source like the GNU GPL v3 license, we could try to add it to F-Droid if you're ok.

**Comment by jordimas** [comment]
Hi 

The license is in the source code files is GLP 2 or later:
https://github.com/Softcatala/LanguageToolAndroidService/blob/master/CorrectorSoftcatala/src/main/java/org/softcatala/corrector/Configuration.java

It's absolutely OK to add this to F-Droid.

Thanks

Jordi,

**Comment by Findus23** [comment]
As much as I like this tool, I think before adding to F-Droid https://github.com/Softcatala/LanguageToolAndroidService/issues/6 needs to fixed, both due to privacy reasons (after all you are sending every you type there) and because I don't know if the server will handle the additional load.

**Comment by jordimas** [comment]
The server handles well the requests. Actually this is why we have a different server.  

If you think that #6 is a requirement feel free to provide a patch and I will code review and integrate it.

Thanks,

Jordi,
